#!/usr/bin/env bash

set -e

if [[ ! $1 ]]; then
    echo "Install location not specified!"
    exit 1
fi

if [[ ! $2 ]]; then
    echo "Target file not specified!"
    exit 1
fi

rootdir=$1
file=$2

mkdir -p $(dirname $file)
echo -n > $file

cat <<EOF >> $file
#!/usr/bin/env bash
export LSCSOFT_LOCATION=$rootdir

# Set up individual modules for development...

EOF

cat <<EOF >> $file
if [[ ! \$LAL_LOCATION ]]; then
    export LAL_LOCATION=\$LSCSOFT_LOCATION
    . \$LAL_LOCATION/etc/lal-user-env.sh &> /dev/null || true
fi

EOF

cat <<EOF >> $file
if [[ ! \$LALFRAME_LOCATION ]]; then
    export LALFRAME_LOCATION=\$LSCSOFT_LOCATION
    . \$LALFRAME_LOCATION/etc/lalframe-user-env.sh &> /dev/null || true
fi

EOF

cat <<EOF >> $file
if [[ ! \$LALMETAIO_LOCATION ]]; then
    export LALMETAIO_LOCATION=\$LSCSOFT_LOCATION
    . \$LALMETAIO_LOCATION/etc/lalmetaio-user-env.sh &> /dev/null || true
fi

EOF

cat <<EOF >> $file
if [[ ! \$LALSIMULATION_LOCATION ]]; then
    export LALSIMULATION_LOCATION=\$LSCSOFT_LOCATION
    . \$LALSIMULATION_LOCATION/etc/lalsimulation-user-env.sh &> /dev/null || true
fi

EOF

cat <<EOF >> $file
if [[ ! \$LALBURST_LOCATION ]]; then
    export LALBURST_LOCATION=\$LSCSOFT_LOCATION
    . \$LALBURST_LOCATION/etc/lalburst-user-env.sh &> /dev/null || true
fi

EOF

cat <<EOF >> $file
if [[ ! \$LALINSPIRAL_LOCATION ]]; then
    export LALINSPIRAL_LOCATION=\$LSCSOFT_LOCATION
    . \$LALINSPIRAL_LOCATION/etc/lalinspiral-user-env.sh &> /dev/null || true
fi

EOF

cat <<EOF >> $file
if [[ ! \$LALSTOCHASTIC_LOCATION ]]; then
    export LALSTOCHASTIC_LOCATION=\$LSCSOFT_LOCATION
    . \$LALSTOCHASTIC_LOCATION/etc/lalstochastic-user-env.sh &> /dev/null || true
fi

EOF

cat <<EOF >> $file
if [[ ! \$LALPULSAR_LOCATION ]]; then
    export LALPULSAR_LOCATION=\$LSCSOFT_LOCATION
    . \$LALPULSAR_LOCATION/etc/lalpulsar-user-env.sh &> /dev/null || true
fi

EOF

cat <<EOF >> $file
if [[ ! \$LALINFERENCE_LOCATION ]]; then
    export LALINFERENCE_LOCATION=\$LSCSOFT_LOCATION
    . \$LALINFERENCE_LOCATION/etc/lalinference-user-env.sh &> /dev/null || true
fi

EOF

cat <<EOF >> $file
if [[ ! \$LALAPPS_LOCATION ]]; then
    export LALAPPS_LOCATION=\$LSCSOFT_LOCATION
    . \$LALAPPS_LOCATION/etc/lalapps-user-env.sh &> /dev/null || true
fi

EOF

cat <<EOF >> $file
if [[ ! \$PYLAL_LOCATION ]]; then
    export PYLAL_LOCATION=\$LSCSOFT_LOCATION
    . \$PYLAL_LOCATION/etc/pylal-user-env.sh &> /dev/null || true
fi

EOF

cat <<EOF >> $file
if [[ ! \$GLUE_LOCATION ]]; then
    export GLUE_LOCATION=\$LSCSOFT_LOCATION
    . \$GLUE_LOCATION/etc/glue-user-env.sh &> /dev/null || true
fi

EOF
