#!/usr/bin/env bash

fail()
{
    local message=${1:-"Something went wrong!"}
    echo $message
    exit 1
}

usage()
{
    cat <<EOF
Usage: install-deps [options] <lscsoft-dir>

Options:

    --frame <src-dir>           Path to libframe source directory.
    --metaio <src-dir>          Path to metaio source directory.
    --user-env <src-dir>        Path to lscsoft-user-env directory.
    -h, --help                  Display this help message.
EOF
    exit 0
}

prog=$(basename "$0")
options=$(getopt --name "$prog" --options hf:m:u: --longoptions help,frame:,metaio:,user-env: -- $@ 2> /dev/null) || fail "Couldn't parse options."
eval set -- "$options"
if [[ $# < 2 ]]; then
    usage
else
    while [[ $# > 0 ]]; do
        case "$1" in
            -f | --frame) libframe=$2; shift;;
            -m | --metaio) metaio=$2; shift;;
            -u | --user-env) lsc_user_env=$2; shift;;
            -h | --help) usage;;
            --) shift; break;;
        esac
        shift
    done
fi

root=$1
[[ ! $root ]] && fail "No root directory given."

capture_uninstall()
{
    # Takes the the name/path of the script to be generated as an argument.
    local target=$1:-"./uninstall.sh"}

    # Make sure directory exists (and file doesn't).
    if [[ ! -d $(dirname $target) ]]; then
        mkdir -p $(dirname $target)
    elif [[ -f $target ]]; then
        rm -f $target
    fi

    echo "#!/usr/bin/env sh" > $target

    local orig_rm=$(which rm)
    cat > rm <<EOF
echo "rm \$*" 1>&3
exit 0
EOF
    chmod +x rm

    orig_PATH=$PATH
    PATH=$(pwd):$PATH
    export PATH
    make uninstall 3>> $target
    PATH=$orig_PATH
    export PATH

    echo "rm -f $target" >> $target
    chmod +x $target
    $orig_rm -f rm
    return 0
}

install_dep()
{
    local src=$1
    local uninstall=$2
    local prefix=$3
    local flags=$4

    [[ ! -d $src ]] && fail "Invalid source directory: $src"

    echo "Installing $src to $prefix"
    mkdir -p $prefix
    pushd $src > /dev/null
    make distclean || true
    ./configure --prefix=$prefix $flags || fail
    make || fail
    make install || fail

     Generate uninstall script.
    capture_uninstall $uninstall || fail
    echo "Uninstall script: $uninstall"

    popd > /dev/null
}

installed=
uninstall_dir=$root/uninstall
if [[ $libframe ]]; then
    installed=true
    install_dep $libframe $uninstall_dir/libframe.sh $root/libframe "--disable-octave --disable-python --with-matlab=no"
fi
if [[ $metaio ]]; then
    installed=true
    install_dep $metaio $uninstall_dir/libmetaio.sh $root/libmetaio
fi
if [[ $lsc_user_env ]]; then
    installed=true
    install_dep $lsc_user_env $uninstall_dir/lscsoft-user-env.sh $root
fi

if [[ -z $installed ]]; then
    echo "Nothing to be done."
fi
